service: cscraper

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-aws-sync

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 128

functions:
  cron:
    handler: scraper.run
    events:
      - schedule: rate(2 minutes)
    environment:
      elasticURL:
        Fn::GetAtt: [ ElasticSearchInstance , DomainEndpoint ]

resources:
  Resources:
    ElasticSearchInstance:
      Type: AWS::Elasticsearch::Domain
      Properties:
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: "6.0"
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:dns}
        AccessControl: PublicRead
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${opt:dns}/*
            - Sid: ListWriteDeleteAccess
              Effect: "Allow"
              Action:
                - s3:ListBucket
                - s3:PutObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::${opt:dns}/*
              Principal:
                  AWS: arn:aws:iam::${opt:user}
    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${opt:dns}.s3.amazonaws.com
              Id: cscraper-app
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          HttpVersion: http2
          Aliases:
           - ${opt:dns}
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: cscraper-app
            ForwardedValues:
              QueryString: true
              QueryStringCacheKeys:
                - v
            ViewerProtocolPolicy: redirect-to-https
  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [ WebAppCloudFrontDistribution, DomainName ]
